# Generated by Django 2.2.4 on 2020-04-16 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard',
            name='date_adopt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wizard',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
